databases:
  - name: farmconnect-db
    databaseName: farmconnect_prod
    user: farmconnect
    plan: free
    ipAllowList: []

services:
  - type: web
    name: farmconnect-backend
    env: node
    plan: free
    region: oregon
    branch: master
    rootDir: farmconnect_backend
    buildCommand: npm install
    startCommand: node src/index.js
    postDeployCommand: node scripts/postdeploy.js
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/farmconnect_backend/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: farmconnect-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      # Optional Twilio/WhatsApp configuration
      - key: TWILIO_ACCOUNT_SID
        value: ""
      - key: TWILIO_AUTH_TOKEN
        value: ""
      - key: TWILIO_PHONE_NUMBER
        value: ""
